version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./yatube/config/.env.dev
  
  web:
    build:
      context: .
      dockerfile: ./yatube/docker/Dockerfile
    command: python -Wd ./yatube/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./yatube/config/.env.dev
    environment:
        DJANGO_DATABASE_HOST: db
    depends_on:
      - db
  

volumes:
  postgres_data:
